.PHONY: clean All

All:
	@echo "----------Building project:[ amqpConnPool - Debug ]----------"
	@"$(MAKE)" -f  "amqpConnPool.mk"
	@echo "----------Building project:[ commonUtils - Debug ]----------"
	@"$(MAKE)" -f  "commonUtils.mk"
	@echo "----------Building project:[ zmqServer - Debug ]----------"
	@"$(MAKE)" -f  "zmqServer.mk"
clean:
	@echo "----------Cleaning project:[ amqpConnPool - Debug ]----------"
	@"$(MAKE)" -f  "amqpConnPool.mk" clean
	@echo "----------Cleaning project:[ commonUtils - Debug ]----------"
	@"$(MAKE)" -f  "commonUtils.mk" clean
	@echo "----------Cleaning project:[ zmqServer - Debug ]----------"
	@"$(MAKE)" -f  "zmqServer.mk" clean
